# Generated by Django 3.0.4 on 2020-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
