# Generated by Django 3.0.4 on 2020-03-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200328_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
