# Generated by Django 3.0.4 on 2020-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200328_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft_status',
            field=models.CharField(default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
