# Generated by Django 3.0.4 on 2020-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200328_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draft_status',
            field=models.IntegerField(default=1),
        ),
    ]
